### PR TITLE
Add updated python-dictdiffer files

### PR DESCRIPTION
**Pull request by danielmellado**
This commit changes python-dictdiffer spec and SRPM according to the
review comments on [1]

[1] https://bugzilla.redhat.com/show_bug.cgi?id=1659281

### CODE REVIEW

**Comment by johnkim76** [comment]
/lgtm

just tested it out via `mock` and it looks good. Thank you for fixing it.

**Comment by johnkim76** [comment]
@danielmellado Should I push up the new srpm separately? or do you want to commit it with this PR?

**Comment by johnkim76** [comment]
@danielmellado nm.. didn't realize you did so already

**Comment by danielmellado** [comment]
@johnkim76 Thanks! I updated it for now as I wasn't sure on your availability. We can leave as it is for now and we'll get back to your repo if there's any needed change. Would that work for you?

Best!

Daniel

**Pull request merged**
